# Generated by Django 4.2.5 on 2023-10-03 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("presence", "0002_player"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("players_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "creation_datetime",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name="player",
            name="creation_datetime",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name="Cell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("players_count", models.PositiveSmallIntegerField(default=0)),
                ("group_colors", models.PositiveIntegerField(default=0)),
                ("build_cost", models.JSONField()),
                ("buy_cost", models.PositiveIntegerField()),
                ("pos", models.PositiveIntegerField(default=0)),
                ("color", models.PositiveIntegerField(default=0)),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="presence.player",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="player",
            name="player",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="presence.room",
            ),
        ),
    ]
