# Generated by Django 4.2.5 on 2023-10-03 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("presence", "0003_room_player_creation_datetime_cell_player_player"),
    ]

    operations = [
        migrations.RenameField(
            model_name="player",
            old_name="player",
            new_name="room",
        ),
        migrations.RemoveField(
            model_name="player",
            name="name",
        ),
        migrations.AddField(
            model_name="player",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
