# Generated by Django 4.2.5 on 2023-10-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("presence", "0004_rename_player_player_room_remove_player_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="player_turn",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="room",
            name="round",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
