# Generated by Django 4.2.5 on 2023-10-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("presence", "0007_user_active_user_color_user_creation_datetime_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="room",
            field=models.ForeignKey(
                null=True, on_delete=models.SET(None), to="presence.room"
            ),
        ),
    ]
