# Generated by Django 4.2.5 on 2023-10-07 06:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("presence", "0010_remove_cell_group_colors"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cell",
            name="build_cost",
        ),
    ]
