# Generated by Django 4.2 on 2024-02-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="room",
            field=models.ForeignKey(
                null=True, on_delete=models.SET(None), to="server.room"
            ),
        ),
    ]
