# Generated by Django 4.2 on 2024-02-19 10:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0003_cell_pawn"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cell",
            name="pawn",
        ),
    ]
