# Generated by Django 4.2 on 2024-03-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0009_room_count_doubles_user_count_roll_in_prison_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cell",
            name="pawn_rounds_remaining",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
