# Generated by Django 4.2 on 2024-03-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0010_cell_pawn_rounds_remaining"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cell",
            name="color",
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
