# Generated by Django 4.2 on 2024-03-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0011_alter_cell_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="lose",
            field=models.BooleanField(default=False),
        ),
    ]
