# Generated by Django 4.2 on 2024-03-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0012_user_lose"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="count_deals",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="user",
            name="pos",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
