# Generated by Django 4.2 on 2024-03-30 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0013_room_count_deals_alter_user_pos"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="build_allowed",
            field=models.BooleanField(default=False),
        ),
    ]
