# Generated by Django 4.2 on 2024-04-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0014_user_build_allowed"),
    ]

    operations = [
        migrations.AddField(
            model_name="cell",
            name="title",
            field=models.CharField(default="0", max_length=50),
            preserve_default=False,
        ),
    ]
