# Generated by Django 4.2 on 2024-04-02 06:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0015_cell_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="cell",
            name="category",
            field=models.CharField(default="1", max_length=50),
            preserve_default=False,
        ),
    ]
